// code/frontend/src/pages/operator/invite-code.tsx
import { useState, useEffect } from 'react'
import { KeyRound, Copy, RefreshCw } from 'lucide-react'
import { getInviteCode, generateInviteCode } from '@/services/operator'
import { toast } from 'sonner'

export default function OperatorInviteCode() {
  const [code, setCode] = useState('')
  const [loading, setLoading] = useState(false)
  const [loadingInit, setLoadingInit] = useState(true)

  useEffect(() => {
    loadCode()
  }, [])

  const loadCode = async () => {
    setLoadingInit(true)
    try {
      const res = await getInviteCode()
      if (res && res.code) {
        setCode(res.code)
      }
    } catch {
      // 还没有邀请码
    } finally {
      setLoadingInit(false)
    }
  }

  const handleCreate = async () => {
    setLoading(true)
    try {
      const res = await generateInviteCode()
      if (res && res.code) {
        setCode(res.code)
        toast.success('邀请码已生成')
      }
    } catch (err: any) {
      toast.error(err.message || '生成失败')
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = () => {
    if (!code) return
    navigator.clipboard.writeText(code)
    toast.success('已复制到剪贴板')
  }

  return (
    <div className="p-6 space-y-4">
      <h1 style={{ fontSize: '24px', fontWeight: 700, color: 'var(--text-primary)' }}>
        邀请码管理
      </h1>

      <div
        style={{
          background: 'var(--card-bg)',
          border: '1px solid var(--card-border)',
          borderRadius: '20px',
          backdropFilter: 'blur(20px)',
          overflow: 'hidden',
        }}
      >
        {/* Card header */}
        <div
          style={{
            padding: '18px 24px',
            borderBottom: '1px solid var(--card-border)',
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
          }}
        >
          <div
            style={{
              width: '32px',
              height: '32px',
              borderRadius: '10px',
              background: 'var(--accent-light)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <KeyRound size={16} style={{ color: 'var(--accent)' }} />
          </div>
          <span style={{ fontSize: '15px', fontWeight: 600, color: 'var(--text-primary)' }}>
            我的邀请码
          </span>
        </div>

        {/* Card body */}
        <div style={{ padding: '32px 24px' }}>
          {loadingInit ? (
            <div style={{ textAlign: 'center', padding: '20px 0' }}>
              <div
                style={{
                  width: '200px',
                  height: '20px',
                  background: 'var(--card-border)',
                  borderRadius: '8px',
                  margin: '0 auto',
                  opacity: 0.5,
                }}
              />
            </div>
          ) : (
            <>
              {/* Code display */}
              <div
                style={{
                  background: 'rgba(30, 41, 59, 0.4)',
                  border: '1px solid var(--card-border)',
                  borderRadius: '14px',
                  padding: '16px 20px',
                  textAlign: 'center',
                  marginBottom: '20px',
                }}
              >
                {code ? (
                  <span
                    style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '22px',
                      fontWeight: 700,
                      color: 'var(--accent)',
                      letterSpacing: '0.12em',
                    }}
                  >
                    {code}
                  </span>
                ) : (
                  <span style={{ fontSize: '15px', color: 'var(--text-muted)' }}>
                    暂无邀请码，点击下方按钮生成
                  </span>
                )}
              </div>

              {/* Buttons */}
              <div style={{ display: 'flex', gap: '12px', justifyContent: 'center' }}>
                <button
                  type="button"
                  onClick={handleCreate}
                  disabled={loading}
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '8px',
                    padding: '10px 22px',
                    borderRadius: '12px',
                    fontSize: '14px',
                    fontWeight: 500,
                    border: 'none',
                    cursor: loading ? 'not-allowed' : 'pointer',
                    background: 'var(--accent)',
                    color: '#fff',
                    opacity: loading ? 0.7 : 1,
                    boxShadow: '0 4px 14px var(--accent-glow)',
                    transition: 'all 0.2s',
                  }}
                  onMouseOver={(e) => { if (!loading) e.currentTarget.style.filter = 'brightness(1.1)' }}
                  onMouseOut={(e) => { e.currentTarget.style.filter = 'none' }}
                >
                  <RefreshCw size={16} className={loading ? 'animate-spin' : ''} />
                  {loading ? '生成中...' : '生成邀请码'}
                </button>

                {code && (
                  <button
                    type="button"
                    onClick={handleCopy}
                    style={{
                      display: 'inline-flex',
                      alignItems: 'center',
                      gap: '8px',
                      padding: '10px 22px',
                      borderRadius: '12px',
                      fontSize: '14px',
                      fontWeight: 500,
                      border: '1px solid var(--card-border)',
                      cursor: 'pointer',
                      background: 'var(--card-bg)',
                      color: 'var(--text-primary)',
                      transition: 'all 0.2s',
                    }}
                    onMouseOver={(e) => {
                      e.currentTarget.style.background = 'var(--accent-light)'
                      e.currentTarget.style.borderColor = 'var(--accent)'
                      e.currentTarget.style.color = 'var(--accent)'
                    }}
                    onMouseOut={(e) => {
                      e.currentTarget.style.background = 'var(--card-bg)'
                      e.currentTarget.style.borderColor = 'var(--card-border)'
                      e.currentTarget.style.color = 'var(--text-primary)'
                    }}
                  >
                    <Copy size={16} />
                    复制邀请码
                  </button>
                )}
              </div>

              {code && (
                <p style={{ fontSize: '13px', color: 'var(--text-muted)', textAlign: 'center', marginTop: '16px' }}>
                  重新生成将使旧邀请码失效
                </p>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  )
}

// code/frontend/src/views/admin/InviteCode.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useThemeStore } from '@/stores/theme'
import { getInviteCode, createInviteCode } from '@/api/admin'
import { message, Modal } from 'ant-design-vue'

const themeStore = useThemeStore()
themeStore.init()

const loading = ref(false)
const currentCode = ref<string | null>(null)
const createdAt = ref<string | null>(null)

async function loadCodes() {
  loading.value = true
  try {
    const code = await getInviteCode()
    currentCode.value = code || null
    createdAt.value = code ? new Date().toISOString() : null
  } catch (e: any) {
    message.error(e?.message || '加载失败')
  } finally {
    loading.value = false
  }
}

async function handleGenerate() {
  if (currentCode.value) {
    Modal.confirm({
      title: '确认生成新邀请码？',
      content: '生成后旧邀请码将立即失效，是否继续？',
      okText: '确认生成',
      cancelText: '取消',
      okButtonProps: { danger: true },
      onOk() {
        doGenerate()
      },
    })
  } else {
    await doGenerate()
  }
}

async function doGenerate() {
  loading.value = true
  try {
    const code = await createInviteCode()
    currentCode.value = code
    createdAt.value = new Date().toISOString()
    message.success('邀请码已生成')
  } catch (e: any) {
    message.error(e?.message || '生成失败')
  } finally {
    loading.value = false
  }
}

function copyCode() {
  if (!currentCode.value) return
  navigator.clipboard.writeText(currentCode.value).then(() => {
    message.success('已复制到剪贴板')
  }).catch(() => {
    message.error('复制失败')
  })
}

loadCodes()
</script>

<template>
  <div id="page-invite-code">
    <div class="cyber-bg-grid"></div>
    <div class="cyber-bg-orb" style="width:500px;height:500px;top:-150px;right:-150px;background:rgba(99,102,241,0.10);"></div>
    <div class="cyber-bg-orb" style="width:400px;height:400px;bottom:10%;left:-100px;background:rgba(236,72,153,0.06);"></div>

    <div class="page-content">
      <div class="page-head">
        <h2><span class="accent-line"></span>邀请码管理</h2>
      </div>

      <!-- 邀请码卡片 -->
      <div class="invite-card" :class="{ 'has-code': !!currentCode }">
        <div class="invite-card-inner">
          <div class="invite-icon">
            <i class="fas fa-qrcode"></i>
          </div>

          <template v-if="currentCode">
            <div class="invite-code-display">{{ currentCode }}</div>
            <div v-if="createdAt" class="invite-meta">生成于 {{ new Date(createdAt).toLocaleString('zh-CN') }}</div>
            <div class="invite-actions">
              <button class="cyber-btn" @click="copyCode">
                <i class="fas fa-copy"></i>复制邀请码
              </button>
              <button class="cyber-btn-primary" @click="handleGenerate" :disabled="loading">
                <i class="fas fa-sync-alt" :class="{ 'fa-spin': loading }"></i>生成新码
              </button>
            </div>
          </template>

          <template v-else>
            <div class="invite-empty">暂无可用邀请码</div>
            <div class="invite-actions">
              <button class="cyber-btn-primary" @click="handleGenerate" :disabled="loading">
                <i class="fas fa-plus" :class="{ 'fa-spin': loading }"></i>生成邀请码
              </button>
            </div>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
#page-invite-code {
  min-height: 100vh;
  padding: 24px;
}
.cyber-bg-grid {
  position: fixed;
  inset: 0;
  background-image:
    linear-gradient(rgba(99,102,241,0.03) 1px, transparent 1px),
    linear-gradient(90deg, rgba(99,102,241,0.03) 1px, transparent 1px);
  background-size: 40px 40px;
  pointer-events: none;
  z-index: 0;
}
.cyber-bg-orb {
  position: fixed;
  border-radius: 50%;
  filter: blur(80px);
  pointer-events: none;
  z-index: 0;
}
.page-content {
  position: relative;
  z-index: 1;
  max-width: 600px;
  margin: 0 auto;
}
.page-head {
  margin-bottom: 32px;
}
.page-head h2 {
  font-size: 20px;
  font-weight: 600;
  color: var(--text-primary);
  display: flex;
  align-items: center;
  gap: 10px;
}
.accent-line {
  display: inline-block;
  width: 4px;
  height: 20px;
  background: linear-gradient(180deg, #6366f1, #8b5cf6);
  border-radius: 2px;
}
.invite-card {
  position: relative;
  z-index: 1;
  overflow: hidden;
  background: var(--bg-card);
  border: 1px solid var(--border-subtle);
  border-radius: 16px;
  padding: 48px 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s ease;
  animation: fadeInUp 0.4s ease-out;
}
.invite-card::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 2px;
  background: linear-gradient(90deg, transparent, var(--accent), transparent);
  animation: borderGlow 3s ease-in-out infinite;
}
.invite-card:hover {
  border-color: var(--border-glow);
  box-shadow: 0 0 24px rgba(var(--accent-rgb), 0.12);
}
.invite-card.has-code {
  border-color: var(--border-glow);
  box-shadow: 0 0 30px rgba(var(--accent-rgb), 0.10);
}
.invite-card-inner {
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
  width: 100%;
}
.invite-icon {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: rgba(99,102,241,0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 24px;
  color: #6366f1;
  margin-bottom: 8px;
}
.invite-code-display {
  font-size: 32px;
  font-weight: 700;
  letter-spacing: 4px;
  color: #6366f1;
  font-family: 'Courier New', monospace;
  background: rgba(99,102,241,0.06);
  border: 1px dashed rgba(99,102,241,0.3);
  border-radius: 8px;
  padding: 16px 32px;
  user-select: all;
}
.invite-meta {
  font-size: 12px;
  color: var(--text-muted);
}
.invite-empty {
  font-size: 16px;
  color: var(--text-muted);
}
.invite-actions {
  display: flex;
  gap: 12px;
  margin-top: 8px;
}
.cyber-btn,
.cyber-btn-primary {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 10px 20px;
  border-radius: 8px;
  border: 1px solid var(--border-color);
  background: var(--card-bg);
  color: var(--text-primary);
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  transition: all 0.2s;
}
.cyber-btn:hover {
  border-color: rgba(99,102,241,0.4);
  color: #6366f1;
}
.cyber-btn-primary {
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  border-color: transparent;
  color: #fff;
}
.cyber-btn-primary:hover {
  opacity: 0.9;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(99,102,241,0.3);
}
.cyber-btn-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  transform: none;
  box-shadow: none;
}
</style>
