// code/frontend/src/pages/auth/register.tsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { UserPlus, Eye, EyeOff, User, Lock, Mail, Key } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'
import { register } from '@/services/auth'

export default function RegisterPage() {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [form, setForm] = useState({
    username: '',
    nickname: '',
    password: '',
    confirmPassword: '',
    inviteCode: '',
  })

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (form.password !== form.confirmPassword) {
      toast.error('两次输入的密码不一致')
      return
    }

    if (form.password.length < 6) {
      toast.error('密码长度不能少于6位')
      return
    }

    setLoading(true)
    try {
      await register({
        username: form.username,
        nickname: form.nickname,
        password: form.password,
        inviteCode: form.inviteCode,
      })
      toast.success('注册成功，请登录')
      navigate('/auth/login')
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : '注册失败'
      toast.error(message)
    } finally {
      setLoading(false)
    }
  }

  const inputStyle = {
    background: 'var(--input-bg)',
    border: '1px solid var(--input-border)',
    color: 'var(--text-primary)',
    transition: 'border-color 0.2s, box-shadow 0.2s, background 0.3s, color 0.3s',
  }

  const floatingLabelStyle = (float: boolean) => ({
    top: float ? '10px' : '50%',
    transform: float ? 'none' : 'translateY(-50%)',
    fontSize: float ? '11px' : '14px',
    color: float ? 'var(--accent)' : 'var(--text-secondary)',
    fontWeight: float ? 500 : 400,
    transition: 'all 0.18s ease',
  })

  return (
    <div className="w-full max-w-[440px] relative z-10">
      {/* Card */}
      <div
        className="relative rounded-[20px] overflow-hidden"
        style={{
          background: 'var(--card-bg)',
          border: '1px solid var(--card-border)',
          backdropFilter: 'blur(24px)',
          WebkitBackdropFilter: 'blur(24px)',
          boxShadow: '0 0 0 1px rgba(59, 130, 246, 0.1), 0 20px 50px rgba(0, 0, 0, 0.5), 0 0 80px rgba(59, 130, 246, 0.08)',
          transition: 'background 0.3s, border-color 0.3s, box-shadow 0.3s',
        }}
      >
        {/* Top accent bar */}
        <div
          className="h-[3px]"
          style={{
            background: 'linear-gradient(90deg, transparent, var(--accent), transparent)',
            boxShadow: '0 0 20px var(--accent-glow)',
          }}
        />

        {/* Inner border */}
        <div
          className="absolute inset-[1px] rounded-[20px] pointer-events-none"
          style={{ border: '1px solid rgba(255, 255, 255, 0.05)' }}
        />

        {/* Card body */}
        <div style={{ padding: '32px 36px 28px' }}>
          <h1 className="text-[24px] font-bold mb-1" style={{ color: 'var(--text-primary)', letterSpacing: '-0.5px', transition: 'color 0.3s' }}>
            创建账号
          </h1>
          <p className="text-[13px] mb-7" style={{ color: 'var(--text-secondary)', transition: 'color 0.3s' }}>
            填写信息完成注册
          </p>

          <form onSubmit={handleSubmit}>
            {/* Form grid */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              {/* Username */}
              <div className="relative" style={{ marginBottom: '16px' }}>
                <input
                  id="reg-username"
                  type="text"
                  placeholder=" "
                  value={form.username}
                  onChange={(e) => setForm({ ...form, username: e.target.value })}
                  required
                  className="peer w-full h-[52px] rounded-xl text-[14px] outline-none"
                  style={{ ...inputStyle, padding: '14px 14px 0' }}
                />
                <label
                  htmlFor="reg-username"
                  className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[14px] pointer-events-none flex items-center gap-2"
                  style={floatingLabelStyle(!!form.username)}
                >
                  <User className="w-[12px] h-[12px] opacity-70" />
                  用户名
                </label>
              </div>

              {/* Nickname */}
              <div className="relative" style={{ marginBottom: '16px' }}>
                <input
                  id="reg-nickname"
                  type="text"
                  placeholder=" "
                  value={form.nickname}
                  onChange={(e) => setForm({ ...form, nickname: e.target.value })}
                  required
                  className="peer w-full h-[52px] rounded-xl text-[14px] outline-none"
                  style={{ ...inputStyle, padding: '14px 14px 0' }}
                />
                <label
                  htmlFor="reg-nickname"
                  className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[14px] pointer-events-none flex items-center gap-2"
                  style={floatingLabelStyle(!!form.nickname)}
                >
                  <Mail className="w-[12px] h-[12px] opacity-70" />
                  昵称
                </label>
              </div>
            </div>

            {/* Password */}
            <div className="relative mb-4">
              <div className="relative">
                <input
                  id="reg-password"
                  type={showPassword ? 'text' : 'password'}
                  placeholder=" "
                  value={form.password}
                  onChange={(e) => setForm({ ...form, password: e.target.value })}
                  required
                  className="peer w-full h-[52px] rounded-xl text-[14px] outline-none pr-10"
                  style={{ ...inputStyle, padding: '14px 44px 0 14px' }}
                />
                <label
                  htmlFor="reg-password"
                  className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[14px] pointer-events-none flex items-center gap-2"
                  style={floatingLabelStyle(!!form.password)}
                >
                  <Lock className="w-[12px] h-[12px] opacity-70" />
                  密码
                </label>
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3.5 top-1/2 -translate-y-1/2 p-1 transition-colors"
                  style={{ color: 'var(--text-secondary)' }}
                  onMouseEnter={(e) => { e.currentTarget.style.color = 'var(--text-primary)' }}
                  onMouseLeave={(e) => { e.currentTarget.style.color = 'var(--text-secondary)' }}
                >
                  {showPassword ? (
                    <EyeOff className="w-[14px] h-[14px]" />
                  ) : (
                    <Eye className="w-[14px] h-[14px]" />
                  )}
                </button>
              </div>
            </div>

            {/* Confirm Password */}
            <div className="relative mb-4">
              <div className="relative">
                <input
                  id="reg-confirm-password"
                  type={showConfirmPassword ? 'text' : 'password'}
                  placeholder=" "
                  value={form.confirmPassword}
                  onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })}
                  required
                  className="peer w-full h-[52px] rounded-xl text-[14px] outline-none pr-10"
                  style={{ ...inputStyle, padding: '14px 44px 0 14px' }}
                />
                <label
                  htmlFor="reg-confirm-password"
                  className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[14px] pointer-events-none flex items-center gap-2"
                  style={floatingLabelStyle(!!form.confirmPassword)}
                >
                  <Lock className="w-[12px] h-[12px] opacity-70" />
                  确认密码
                </label>
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-3.5 top-1/2 -translate-y-1/2 p-1 transition-colors"
                  style={{ color: 'var(--text-secondary)' }}
                  onMouseEnter={(e) => { e.currentTarget.style.color = 'var(--text-primary)' }}
                  onMouseLeave={(e) => { e.currentTarget.style.color = 'var(--text-secondary)' }}
                >
                  {showConfirmPassword ? (
                    <EyeOff className="w-[14px] h-[14px]" />
                  ) : (
                    <Eye className="w-[14px] h-[14px]" />
                  )}
                </button>
              </div>
            </div>

            {/* Invite Code */}
            <div className="relative mb-6">
              <input
                id="reg-invite-code"
                type="text"
                placeholder=" "
                value={form.inviteCode}
                onChange={(e) => setForm({ ...form, inviteCode: e.target.value })}
                className="peer w-full h-[52px] rounded-xl text-[14px] outline-none"
                style={{ ...inputStyle, padding: '14px 14px 0' }}
              />
              <label
                htmlFor="reg-invite-code"
                className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[14px] pointer-events-none flex items-center gap-2"
                style={floatingLabelStyle(!!form.inviteCode)}
              >
                <Key className="w-[12px] h-[12px] opacity-70" />
                邀请码（可选）
              </label>
            </div>

            {/* Submit button */}
            <Button
              type="submit"
              className="w-full h-[52px] rounded-xl text-[15px] font-semibold text-white transition-all duration-200 active:scale-[0.97] flex items-center justify-center gap-2"
              disabled={loading}
              style={{
                background: 'var(--accent)',
                boxShadow: '0 4px 16px var(--accent-glow)',
                transition: 'transform 0.2s, box-shadow 0.2s, filter 0.2s, background 0.3s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = 'translateY(-2px)'
                e.currentTarget.style.boxShadow = '0 8px 24px var(--accent-glow)'
                e.currentTarget.style.filter = 'brightness(1.05)'
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = ''
                e.currentTarget.style.boxShadow = '0 4px 16px var(--accent-glow)'
                e.currentTarget.style.filter = ''
              }}
            >
              <UserPlus className="w-[15px] h-[15px]" />
              {loading ? '注册中...' : '注 册'}
            </Button>
          </form>
        </div>

        {/* Card footer */}
        <div style={{ padding: '0 36px 28px', textAlign: 'center' }}>
          <p className="text-[13px]" style={{ color: 'var(--text-secondary)', marginTop: '16px', transition: 'color 0.3s' }}>
            已有账号？<Link to="/auth/login" style={{ color: 'var(--accent)', textDecoration: 'none', fontWeight: 500 }}>立即登录</Link>
          </p>
        </div>
      </div>
    </div>
  )
}

// code/frontend/src/views/auth/Register.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { authApi } from '@/api/auth'
import ThemeToggleBtn from '@/components/layout/ThemeToggleBtn.vue'

const router = useRouter()

const form = ref({
  username: '',
  nickname: '',
  password: '',
  confirmPassword: '',
  inviteCode: '',
})
const loading = ref(false)

async function handleRegister() {
  if (!form.value.username || !form.value.nickname || !form.value.password) {
    message.error('请填写完整信息')
    return
  }
  if (form.value.password !== form.value.confirmPassword) {
    message.error('两次密码输入不一致')
    return
  }
  if (!form.value.inviteCode) {
    message.error('请输入邀请码')
    return
  }

  loading.value = true
  try {
    await authApi.register({
      username: form.value.username,
      nickname: form.value.nickname,
      password: form.value.password,
      confirmPassword: form.value.confirmPassword,
      inviteCode: form.value.inviteCode,
    })
    message.success('注册成功，请等待审核')
    router.push('/login')
  } catch (e: any) {
    message.error(e?.message || '注册失败')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div id="page-register">
    <!-- BG -->
    <div class="cyber-bg-grid"></div>
    <div class="cyber-bg-orb" style="width:400px;height:400px;top:-100px;right:-100px;background:rgba(99,102,241,0.12);"></div>
    <div class="cyber-bg-orb" style="width:300px;height:300px;bottom:10%;left:-80px;background:rgba(236,72,153,0.08);"></div>

    <!-- 注册卡片 -->
    <div class="login-card cyber-card">
      <div class="logo">P</div>
      <h1>创建账号</h1>
      <p class="sub">// JOIN_POINTS_MALL</p>

      <form @submit.prevent="handleRegister">
        <div class="field">
          <label>用户名</label>
          <div class="input-wrap">
            <i class="fas fa-user"></i>
            <input
              v-model="form.username"
              type="text"
              placeholder="请输入用户名"
            />
          </div>
        </div>

        <div class="field">
          <label>昵称</label>
          <div class="input-wrap">
            <i class="fas fa-id-card"></i>
            <input
              v-model="form.nickname"
              type="text"
              placeholder="请输入昵称"
            />
          </div>
        </div>

        <div class="field">
          <label>密码</label>
          <div class="input-wrap">
            <i class="fas fa-lock"></i>
            <input
              v-model="form.password"
              type="password"
              placeholder="请输入密码"
            />
          </div>
        </div>

        <div class="field">
          <label>确认密码</label>
          <div class="input-wrap">
            <i class="fas fa-lock"></i>
            <input
              v-model="form.confirmPassword"
              type="password"
              placeholder="请再次输入密码"
            />
          </div>
        </div>

        <div class="field">
          <label>邀请码</label>
          <div class="input-wrap">
            <i class="fas fa-ticket-alt"></i>
            <input
              v-model="form.inviteCode"
              type="text"
              placeholder="请输入邀请码"
            />
          </div>
        </div>

        <div class="actions">
          <button type="submit" class="cyber-btn-primary" :disabled="loading">
            <i class="fas fa-user-plus" style="margin-right:6px;"></i>
            {{ loading ? '注册中...' : '注 册' }}
          </button>
          <button type="button" class="cyber-btn" @click="router.push('/login')">
            <i class="fas fa-arrow-left" style="margin-right:6px;"></i>
            返回登录
          </button>
        </div>
      </form>
    </div>

    <!-- 主题切换按钮 -->
    <ThemeToggleBtn />
  </div>
</template>

<style scoped>
#page-register {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 20px;
  position: relative;
  overflow: hidden;
}

.login-card {
  position: relative;
  z-index: 1;
  width: 400px;
  max-width: 100%;
  padding: 44px 40px;
  animation: scaleIn 0.5s ease-out, fadeInUp 0.5s ease-out;
  overflow: hidden;
}

.login-card::before {
  content: '';
  position: absolute;
  top: 0; left: 0; right: 0;
  height: 2px;
  background: linear-gradient(90deg, transparent, var(--accent), transparent);
  animation: borderGlow 3s ease-in-out infinite;
}

.logo {
  width: 48px;
  height: 48px;
  border-radius: var(--radius-sm);
  background: linear-gradient(135deg, var(--accent), var(--pink));
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-size: 22px;
  font-weight: bold;
  box-shadow: var(--accent-glow);
  margin-bottom: 28px;
}

.login-card h1 {
  font-size: 28px;
  font-weight: 800;
  margin-bottom: 4px;
  background: linear-gradient(135deg, var(--text-primary) 0%, var(--accent-light) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.login-card .sub {
  font-size: 14px;
  color: var(--text-muted);
  font-family: var(--font-mono);
  margin-bottom: 32px;
  letter-spacing: 0.5px;
}

.field {
  margin-bottom: 18px;
}

.field label {
  display: block;
  font-size: 12px;
  font-weight: 600;
  color: var(--text-secondary);
  margin-bottom: 7px;
  letter-spacing: 0.5px;
  text-transform: uppercase;
}

.input-wrap {
  display: flex;
  align-items: center;
  background: var(--bg-input);
  border: 1px solid var(--border-subtle);
  border-radius: var(--radius-sm);
  padding: 0 14px;
  transition: all 0.2s ease;
}

.input-wrap:focus-within {
  border-color: var(--border-active);
  box-shadow: 0 0 0 3px rgba(var(--accent-rgb), 0.10);
}

.input-wrap i {
  color: var(--text-muted);
  font-size: 14px;
  margin-right: 10px;
  width: 16px;
  text-align: center;
}

.input-wrap input {
  flex: 1;
  border: none;
  background: transparent;
  padding: 11px 0;
  color: var(--text-primary);
  font-size: 14px;
  outline: none;
  font-family: inherit;
}

.input-wrap input::placeholder {
  color: var(--text-muted);
}

.actions {
  margin-top: 28px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.actions button {
  width: 100%;
  justify-content: center;
  display: flex;
  align-items: center;
}
</style>
