// code/frontend/src/views/operator/Messages.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { operatorApi } from '@/api/operator'
import type { Message } from '@/types'

const loading = ref(false)
const messages = ref<Message[]>([])
const pagination = ref({ page: 1, pageSize: 10, total: 0 })

async function fetchMessages() {
  loading.value = true
  try {
    const res = await operatorApi.getMessages({ page: pagination.value.page, pageSize: pagination.value.pageSize })
    messages.value = res.data.list
    pagination.value.total = res.data.total
  } catch (e) {
    console.error(e)
  } finally {
    loading.value = false
  }
}

function handlePageChange(page: number) {
  pagination.value.page = page
  fetchMessages()
}

onMounted(fetchMessages)
</script>

<template>
  <div class="space-y-6">
    <h2 class="text-2xl font-bold text-gray-800">消息中心</h2>

    <div class="bg-white rounded-xl shadow-sm overflow-hidden">
      <div class="divide-y divide-gray-200">
        <div
          v-for="msg in messages"
          :key="msg.id"
          :class="['p-4 hover:bg-gray-50', !msg.isRead ? 'bg-purple-50' : '']"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="flex items-center gap-2">
                <span
                  :class="['px-2 py-0.5 text-xs font-medium rounded-full', msg.type === 'ORDER' ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-800']"
                >
                  {{ msg.type === 'ORDER' ? '订单' : '系统' }}
                </span>
                <span v-if="!msg.isRead" class="w-2 h-2 bg-purple-600 rounded-full"></span>
              </div>
              <h4 class="font-medium text-gray-800 mt-1">{{ msg.title }}</h4>
              <p class="text-sm text-gray-500 mt-1">{{ msg.content }}</p>
              <p class="text-xs text-gray-400 mt-2">{{ msg.createTime }}</p>
            </div>
          </div>
        </div>
        <div v-if="messages.length === 0" class="p-12 text-center text-gray-500">
          暂无消息
        </div>
      </div>

      <div class="px-6 py-4 border-t border-gray-200 flex justify-center">
        <div class="flex gap-2">
          <button
            v-for="page in Math.ceil(pagination.total / pagination.pageSize)"
            :key="page"
            @click="handlePageChange(page)"
            :class="[
              'px-3 py-1 text-sm rounded-md',
              page === pagination.page ? 'bg-purple-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            ]"
          >
            {{ page }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// code/frontend/src/pages/user/messages.tsx
import { useState, useEffect } from 'react'
import { MessageSquare, Mail, Loader2, CheckCircle } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { toast } from 'sonner'
import { getMessages, readMessage, type Message } from '@/services/user'

export default function MessagesPage() {
  const [loading, setLoading] = useState(true)
  const [messages, setMessages] = useState<Message[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize] = useState(10)
  const [readingId, setReadingId] = useState<string | null>(null)

  const fetchMessages = async () => {
    setLoading(true)
    try {
      const res = await getMessages({ page, pageSize })
      setMessages(res.list)
      setTotal(res.total)
    } catch (err: any) {
      toast.error(err.message || '获取消息列表失败')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchMessages()
  }, [page])

  const handleRead = async (id: string) => {
    const msg = messages.find((m) => m.id === id)
    if (msg?.isRead === 1) return

    setReadingId(id)
    try {
      await readMessage(id)
      setMessages((prev) =>
        prev.map((m) => (m.id === id ? { ...m, isRead: 1 } : m))
      )
    } catch (err: any) {
      toast.error(err.message || '标记已读失败')
    } finally {
      setReadingId(null)
    }
  }

  const totalPages = Math.ceil(total / pageSize)

  return (
    <div className="max-w-2xl mx-auto p-4 space-y-6">
      <div className="flex items-center gap-2">
        <MessageSquare className="w-5 h-5" />
        <h1 className="text-xl font-semibold">消息中心</h1>
      </div>

      {loading ? (
        <div className="space-y-4">
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-20 w-full" />
          ))}
        </div>
      ) : messages.length === 0 ? (
        <div className="text-center py-12 text-muted-foreground">
          <Mail className="w-12 h-12 mx-auto mb-4 opacity-50" />
          <p>暂无消息</p>
        </div>
      ) : (
        <div className="space-y-4">
          {messages.map((msg) => (
            <Card
              key={msg.id}
              className={`cursor-pointer hover:bg-muted/30 transition-colors ${
                msg.isRead === 1 ? 'opacity-60' : ''
              }`}
              onClick={() => handleRead(msg.id)}
            >
              <CardContent className="p-4">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <h3 className="font-medium">{msg.title}</h3>
                      {msg.isRead === 1 ? (
                        <Badge variant="outline" className="text-xs">已读</Badge>
                      ) : (
                        <Badge variant="default" className="text-xs">未读</Badge>
                      )}
                    </div>
                    <p className="text-sm text-muted-foreground mt-2 line-clamp-2">
                      {msg.content}
                    </p>
                    <p className="text-xs text-muted-foreground mt-2">
                      {new Date(msg.createTime).toLocaleString()}
                    </p>
                  </div>
                  {msg.isRead !== 1 && readingId === msg.id && (
                    <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
                  )}
                  {msg.isRead === 1 && (
                    <CheckCircle className="w-4 h-4 text-muted-foreground" />
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex justify-center gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={page === 1}
            onClick={() => setPage(page - 1)}
          >
            上一页
          </Button>
          <span className="px-3 py-2 text-sm">
            {page} / {totalPages}
          </span>
          <Button
            variant="outline"
            size="sm"
            disabled={page === totalPages}
            onClick={() => setPage(page + 1)}
          >
            下一页
          </Button>
        </div>
      )}
    </div>
  )
}
