// code/frontend/src/views/admin/InviteCode.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useThemeStore } from '@/stores/theme'
import { getInviteCode, createInviteCode } from '@/api/admin'
import { message, Modal } from 'ant-design-vue'

const themeStore = useThemeStore()
themeStore.init()

const loading = ref(false)
const currentCode = ref<string | null>(null)
const createdAt = ref<string | null>(null)

async function loadCodes() {
  loading.value = true
  try {
    const code = await getInviteCode()
    currentCode.value = code || null
    createdAt.value = code ? new Date().toISOString() : null
  } catch (e: any) {
    message.error(e?.message || '加载失败')
  } finally {
    loading.value = false
  }
}

async function handleGenerate() {
  if (currentCode.value) {
    Modal.confirm({
      title: '确认生成新邀请码？',
      content: '生成后旧邀请码将立即失效，是否继续？',
      okText: '确认生成',
      cancelText: '取消',
      okButtonProps: { danger: true },
      onOk() {
        doGenerate()
      },
    })
  } else {
    await doGenerate()
  }
}

async function doGenerate() {
  loading.value = true
  try {
    const code = await createInviteCode()
    currentCode.value = code
    createdAt.value = new Date().toISOString()
    message.success('邀请码已生成')
  } catch (e: any) {
    message.error(e?.message || '生成失败')
  } finally {
    loading.value = false
  }
}

function copyCode() {
  if (!currentCode.value) return
  navigator.clipboard.writeText(currentCode.value).then(() => {
    message.success('已复制到剪贴板')
  }).catch(() => {
    message.error('复制失败')
  })
}

loadCodes()
</script>

<template>
  <div id="page-invite-code">
    <div class="cyber-bg-grid"></div>
    <div class="cyber-bg-orb" style="width:500px;height:500px;top:-150px;right:-150px;background:rgba(99,102,241,0.10);"></div>
    <div class="cyber-bg-orb" style="width:400px;height:400px;bottom:10%;left:-100px;background:rgba(236,72,153,0.06);"></div>

    <div class="page-content">
      <div class="page-head">
        <h2><span class="accent-line"></span>邀请码管理</h2>
      </div>

      <!-- 邀请码卡片 -->
      <div class="invite-card" :class="{ 'has-code': !!currentCode }">
        <div class="invite-card-inner">
          <div class="invite-icon">
            <i class="fas fa-qrcode"></i>
          </div>

          <template v-if="currentCode">
            <div class="invite-code-display">{{ currentCode }}</div>
            <div v-if="createdAt" class="invite-meta">生成于 {{ new Date(createdAt).toLocaleString('zh-CN') }}</div>
            <div class="invite-actions">
              <button class="cyber-btn" @click="copyCode">
                <i class="fas fa-copy"></i>复制邀请码
              </button>
              <button class="cyber-btn-primary" @click="handleGenerate" :disabled="loading">
                <i class="fas fa-sync-alt" :class="{ 'fa-spin': loading }"></i>生成新码
              </button>
            </div>
          </template>

          <template v-else>
            <div class="invite-empty">暂无可用邀请码</div>
            <div class="invite-actions">
              <button class="cyber-btn-primary" @click="handleGenerate" :disabled="loading">
                <i class="fas fa-plus" :class="{ 'fa-spin': loading }"></i>生成邀请码
              </button>
            </div>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
#page-invite-code {
  min-height: 100vh;
  padding: 24px;
}
.cyber-bg-grid {
  position: fixed;
  inset: 0;
  background-image:
    linear-gradient(rgba(99,102,241,0.03) 1px, transparent 1px),
    linear-gradient(90deg, rgba(99,102,241,0.03) 1px, transparent 1px);
  background-size: 40px 40px;
  pointer-events: none;
  z-index: 0;
}
.cyber-bg-orb {
  position: fixed;
  border-radius: 50%;
  filter: blur(80px);
  pointer-events: none;
  z-index: 0;
}
.page-content {
  position: relative;
  z-index: 1;
  max-width: 600px;
  margin: 0 auto;
}
.page-head {
  margin-bottom: 32px;
}
.page-head h2 {
  font-size: 20px;
  font-weight: 600;
  color: var(--text-primary);
  display: flex;
  align-items: center;
  gap: 10px;
}
.accent-line {
  display: inline-block;
  width: 4px;
  height: 20px;
  background: linear-gradient(180deg, #6366f1, #8b5cf6);
  border-radius: 2px;
}
.invite-card {
  position: relative;
  z-index: 1;
  overflow: hidden;
  background: var(--bg-card);
  border: 1px solid var(--border-subtle);
  border-radius: 16px;
  padding: 48px 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s ease;
  animation: fadeInUp 0.4s ease-out;
}
.invite-card::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 2px;
  background: linear-gradient(90deg, transparent, var(--accent), transparent);
  animation: borderGlow 3s ease-in-out infinite;
}
.invite-card:hover {
  border-color: var(--border-glow);
  box-shadow: 0 0 24px rgba(var(--accent-rgb), 0.12);
}
.invite-card.has-code {
  border-color: var(--border-glow);
  box-shadow: 0 0 30px rgba(var(--accent-rgb), 0.10);
}
.invite-card-inner {
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
  width: 100%;
}
.invite-icon {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: rgba(99,102,241,0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 24px;
  color: #6366f1;
  margin-bottom: 8px;
}
.invite-code-display {
  font-size: 32px;
  font-weight: 700;
  letter-spacing: 4px;
  color: #6366f1;
  font-family: 'Courier New', monospace;
  background: rgba(99,102,241,0.06);
  border: 1px dashed rgba(99,102,241,0.3);
  border-radius: 8px;
  padding: 16px 32px;
  user-select: all;
}
.invite-meta {
  font-size: 12px;
  color: var(--text-muted);
}
.invite-empty {
  font-size: 16px;
  color: var(--text-muted);
}
.invite-actions {
  display: flex;
  gap: 12px;
  margin-top: 8px;
}
.cyber-btn,
.cyber-btn-primary {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 10px 20px;
  border-radius: 8px;
  border: 1px solid var(--border-color);
  background: var(--card-bg);
  color: var(--text-primary);
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  transition: all 0.2s;
}
.cyber-btn:hover {
  border-color: rgba(99,102,241,0.4);
  color: #6366f1;
}
.cyber-btn-primary {
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  border-color: transparent;
  color: #fff;
}
.cyber-btn-primary:hover {
  opacity: 0.9;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(99,102,241,0.3);
}
.cyber-btn-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  transform: none;
  box-shadow: none;
}
</style>

// code/frontend/src/pages/admin/invite-code.tsx
import { useState, useEffect } from 'react'
import { KeyRound, Copy, RefreshCw, Check } from 'lucide-react'
import { getInviteCode, generateInviteCode } from '@/services/admin'
import { toast } from 'sonner'

export default function AdminInviteCode() {
  const [code, setCode] = useState('')
  const [loading, setLoading] = useState(false)
  const [loadingInit, setLoadingInit] = useState(true)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    loadCode()
  }, [])

  const loadCode = async () => {
    setLoadingInit(true)
    try {
      const res: any = await getInviteCode()
      if (typeof res === 'string') {
        setCode(res)
      } else if (res?.code) {
        setCode(res.code)
      }
    } catch {
      // 还没有邀请码
    } finally {
      setLoadingInit(false)
    }
  }

  const handleCreate = async () => {
    setLoading(true)
    try {
      const res: any = await generateInviteCode()
      if (typeof res === 'string') {
        setCode(res)
        toast.success('邀请码已生成')
      } else if (res?.code) {
        setCode(res.code)
        toast.success('邀请码已生成')
      }
    } catch (err: any) {
      toast.error(err.message || '生成失败')
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = () => {
    if (!code) return
    navigator.clipboard.writeText(code)
    setCopied(true)
    toast.success('已复制到剪贴板')
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div style={{ padding: '24px' }}>
      {/* Page Header */}
      <div style={{ marginBottom: '32px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 700, color: 'var(--text-primary)' }}>邀请码管理</h1>
        <p style={{ fontSize: '14px', color: 'var(--text-secondary)', marginTop: '4px' }}>管理员邀请码</p>
      </div>

      {/* Loading skeleton */}
      {loadingInit ? (
        <div
          className="glass-card"
          style={{ padding: '24px', textAlign: 'center' }}
        >
          <div style={{ color: 'var(--text-muted)', fontSize: '14px' }}>加载中...</div>
        </div>
      ) : (
        <div
          style={{
            maxWidth: '520px',
          }}
        >
          <div
            style={{
              background: 'var(--card-bg)',
              border: '1px solid var(--card-border)',
              borderRadius: '20px',
              backdropFilter: 'blur(20px)',
              overflow: 'hidden',
            }}
          >
            {/* Gradient accent bar */}
            <div
              style={{
                height: '4px',
                background: 'linear-gradient(90deg, var(--accent), #a78bfa, var(--accent))',
                backgroundSize: '200% 100%',
              }}
            />

            {/* Card header */}
            <div
              style={{
                padding: '20px 24px',
                borderBottom: '1px solid var(--card-border)',
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
              }}
            >
              <div
                style={{
                  width: '36px',
                  height: '36px',
                  borderRadius: '10px',
                  background: 'var(--accent-light)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <KeyRound size={18} style={{ color: 'var(--accent)' }} />
              </div>
              <div>
                <div style={{ fontSize: '15px', fontWeight: 600, color: 'var(--text-primary)' }}>
                  管理员邀请码
                </div>
                <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '2px' }}>
                  用于邀请新管理员注册
                </div>
              </div>
            </div>

            {/* Card body */}
            <div style={{ padding: '28px 24px' }}>
              {/* Code display */}
              <div
                style={{
                  background: 'linear-gradient(135deg, rgba(59,130,246,0.08), rgba(139,92,246,0.08))',
                  border: '1px solid var(--card-border)',
                  borderRadius: '14px',
                  padding: '24px',
                  textAlign: 'center',
                  marginBottom: '20px',
                  position: 'relative',
                }}
              >
                {code ? (
                  <>
                    <div
                      style={{
                        fontFamily: 'monospace',
                        fontSize: '28px',
                        fontWeight: 700,
                        color: 'var(--accent)',
                        letterSpacing: '0.15em',
                        marginBottom: '8px',
                        userSelect: 'all',
                      }}
                    >
                      {code}
                    </div>
                    <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
                      复制此邀请码并发送给新管理员
                    </div>
                  </>
                ) : (
                  <div
                    style={{
                      display: 'flex',
                      flexDirection: 'column',
                      alignItems: 'center',
                      gap: '12px',
                      padding: '8px 0',
                    }}
                  >
                    <KeyRound size={36} style={{ color: 'var(--text-muted)', opacity: 0.4 }} />
                    <div>
                      <div style={{ fontSize: '15px', fontWeight: 500, color: 'var(--text-secondary)', marginBottom: '4px' }}>
                        暂无邀请码
                      </div>
                      <div style={{ fontSize: '13px', color: 'var(--text-muted)' }}>
                        点击下方按钮生成一个新的邀请码
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Buttons */}
              <div style={{ display: 'flex', gap: '12px' }}>
                <button
                  type="button"
                  onClick={handleCopy}
                  disabled={!code}
                  style={{
                    flex: 1,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '8px',
                    padding: '12px 20px',
                    borderRadius: '12px',
                    fontSize: '14px',
                    fontWeight: 500,
                    border: `1px solid var(--card-border)`,
                    background: code ? 'var(--card-bg)' : 'var(--card-bg)',
                    color: code ? 'var(--text-primary)' : 'var(--text-muted)',
                    cursor: code ? 'pointer' : 'not-allowed',
                    opacity: code ? 1 : 0.5,
                    transition: 'all 0.2s',
                  }}
                  onMouseEnter={(e) => {
                    if (code) {
                      e.currentTarget.style.borderColor = 'var(--accent)'
                      e.currentTarget.style.background = 'var(--accent-light)'
                    }
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.borderColor = 'var(--card-border)'
                    e.currentTarget.style.background = 'var(--card-bg)'
                  }}
                >
                  {copied ? <Check size={16} style={{ color: '#10b981' }} /> : <Copy size={16} />}
                  {copied ? '已复制' : '复制邀请码'}
                </button>

                <button
                  type="button"
                  onClick={handleCreate}
                  disabled={loading}
                  style={{
                    flex: 1,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '8px',
                    padding: '12px 20px',
                    borderRadius: '12px',
                    fontSize: '14px',
                    fontWeight: 500,
                    border: 'none',
                    background: 'var(--accent)',
                    color: '#fff',
                    cursor: loading ? 'not-allowed' : 'pointer',
                    opacity: loading ? 0.7 : 1,
                    boxShadow: '0 4px 14px var(--accent-glow)',
                    transition: 'all 0.2s',
                  }}
                  onMouseEnter={(e) => {
                    if (!loading) {
                      e.currentTarget.style.opacity = '0.9'
                      e.currentTarget.style.transform = 'translateY(-1px)'
                    }
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.opacity = '1'
                    e.currentTarget.style.transform = 'translateY(0)'
                  }}
                >
                  <RefreshCw
                    size={16}
                    style={{
                      animation: loading ? 'spin 1s linear infinite' : 'none',
                    }}
                  />
                  {loading ? '生成中...' : '生成新邀请码'}
                </button>
              </div>

              {/* Note */}
              <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '16px', textAlign: 'center' }}>
                重新生成将使之前的邀请码失效
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
